from tkinter import *
import random
import time;
import datetime
from tkinter import messagebox
import os
from tkinter import ttk
root = Tk()
root.geometry("1366x768")
root.title("Cafe Management Systems")
#======================================Title Frame================================================
TopFrame0 = Frame(root, width = 1366, height = 50, bd = 14, relief ="raise", background = "light blue")
TopFrame0.pack(side=TOP)
TopFrame1 = Frame(root, width = 1366, height = 50, bd = 14, relief ="raise", background = "light green")
TopFrame1.pack(side=TOP)
TopFrame2 = Frame(root, width = 1366, height = 50, bd = 14, relief ="raise", background ="light blue")
TopFrame2.pack(side=TOP)
TitleFrame = Label(TopFrame1, font=('arial',20, 'bold'),text = "\t\t\t\t\tClick & Collect Menu\t\t\t\t\t\t\t\t",bd=10, background = "light green")
TitleFrame.grid(row=1,column=0)

#======================================================Exit button function===================================
def ExitButton():
    ExitButton = messagebox.askyesno("Quit System", "Do you want to quit?")
    if ExitButton > 0:
        root.destroy()
        return
#======================================================Reset Data function======================================
def ResetData():
    PaidTax.set("")
    SubTotal.set("")
    TotalCost.set("")
    CostofDrinks.set("")
    CostofMeals.set("")
    WaiterTip.set("")
    Cafe_Nachos.set("0")
    Cafe_Chicken_Sandwich.set("0")
    Cafe_Sausage_Roll.set("0")
    Cafe_Hotdog.set("0")
    Cafe_Pizza_Bread.set("0")
    Cafe_Pizza.set("0")
    Cafe_Steam_Bun.set("0")
    Cafe_Soup.set("0")
    Cafe_Water.set("0")
    Cafe_Barista_Bros.set("0")
    Cafe_Lipton_Light.set("0")
    Cafe_Hot_Chocolate.set("0")
    Cafe_Aloe_Drink.set("0")
    Cafe_Orange_Juice.set("0")
    Cafe_Calci_Yum.set("0")
    Cafe_Flavoured_Water.set("0")
    ItemVar1.set("0")
    ItemVar2.set("0")
    ItemVar3.set("0")
    ItemVar4.set("0")
    ItemVar5.set("0")
    ItemVar6.set("0")
    ItemVar7.set("0")
    ItemVar8.set("0")
    ItemVar9.set("0")
    ItemVar10.set("0")
    ItemVar11.set("0")
    ItemVar12.set("0")
    ItemVar13.set("0")
    ItemVar14.set("0")
    ItemVar15.set("0")
    ItemVar16.set("0")
    EntryNachos.configure(state = DISABLED)
    EntryChicken_Sandwich.configure(state = DISABLED)
    EntrySausage_Roll.configure(state = DISABLED)
    EntryHotdog.configure(state = DISABLED)
    EntryPizza_Bread.configure(state = DISABLED)
    EntryPizza.configure(state = DISABLED)
    EntrySteam_Bun.configure(state = DISABLED)
    EntrySoup.configure(state = DISABLED)
#======================================================Cost of Item function=============================
def CostofItem():
    ButtonReceipt = Button(MainFrontOne, padx = 16, pady = 1, bd =4,font=('arial', 10, 'bold'), width = 5, text = "Receipt", command = Receipt, state = NORMAL).grid(row=0, column=1)
    Item1=float(Cafe_Nachos.get())
    Item2=float(Cafe_Chicken_Sandwich.get())
    Item3=float(Cafe_Sausage_Roll.get())
    Item4=float(Cafe_Hotdog.get())
    Item5=float(Cafe_Pizza_Bread.get())
    Item6=float(Cafe_Pizza.get())
    Item7=float(Cafe_Steam_Bun.get())
    Item8=float(Cafe_Soup.get())
    Item9=float(Cafe_Water.get())
    Item10=float(Cafe_Barista_Bros.get())
    Item11=float(Cafe_Lipton_Light.get())
    Item12=float(Cafe_Hot_Chocolate.get())
    Item13=float(Cafe_Aloe_Drink.get())
    Item14=float(Cafe_Orange_Juice.get())
    Item15=float(Cafe_Calci_Yum.get())
    Item16=float(Cafe_Flavoured_Water.get())
    PriceofDrinks = (Item1 * 1.2) + (Item2 * 1.99) + (Item3 * 2.05) + (Item4 * 1.89) + (Item5 * 1.99) + (Item6 * 2.99) + (Item7 * 2.39) + (Item8 * 1.29) 
    PriceofMeals = (Item9 * 1.35) + (Item10 * 2.2) + (Item11 * 1.99) + (Item12 * 1.49) + (Item13 * 1.8) + (Item14 * 1.67) + (Item15 * 1.6) + (Item16 * 1.99)
    DrinksPrice = "$", str('%.2f'%(PriceofDrinks))
    MealsPrice = "$", str('%.2f'%(PriceofMeals))
    CostofMeals.set(MealsPrice)
    CostofDrinks.set(DrinksPrice)
    SC = "$", str('%.2f'%(1.59))
    WaiterTip.set(SC)

    SubTotalofITEMS = "$", str('%.2f'%(PriceofDrinks + PriceofMeals + 1.59))
    SubTotal.set(SubTotalofITEMS)

    Tax = "$", str('%.2f'%((PriceofDrinks + PriceofMeals + 1.59)*0.15))
    PaidTax.set(Tax)
    TT = ((PriceofDrinks + PriceofMeals + 1.59)*0.15)
    TC = "$", str ('%.2f'%(PriceofDrinks + PriceofMeals + 1.59 + TT))
    TotalCost.set(TC)
def Receipt():
    Receipt_Text.delete("1.0", END)
    x = random.randint(10908, 500876)
    randomRef = str(x)
    Receipt_Ref.set("BILL"+ randomRef)
    Receipt_Text.insert(END, 'Receipt Ref:\t\t\t' + Receipt_Ref.get()+'\t\t' + DateofOrder.get()+"\n")
    Receipt_Text.insert(END, 'Items:\t\t\t' + "Cost of Items \n\n")
    Receipt_Text.insert(END, 'Nachos:\t\t\t' + Cafe_Nachos.get() + "\n")
    Receipt_Text.insert(END, 'ChickenSandwich:\t\t\t'  + Cafe_Chicken_Sandwich.get() + "\n")
    Receipt_Text.insert(END, 'SausageRoll:\t\t\t'  + Cafe_Sausage_Roll.get() + "\n")
    Receipt_Text.insert(END, 'Hot dog:\t\t\t'  + Cafe_Hotdog.get() + "\n")
    Receipt_Text.insert(END, 'PizzaBread:\t\t\t'  + Cafe_Pizza_Bread.get() + "\n")
    Receipt_Text.insert(END, 'SteamBun:\t\t\t'  + Cafe_Steam_Bun.get() + "\n")
    Receipt_Text.insert(END, 'Soup:\t\t\t'  + Cafe_Soup.get() + "\n")
    Receipt_Text.insert(END, 'Water:\t\t\t' + Cafe_Water.get() + "\n")
    Receipt_Text.insert(END, 'Barista Bros:\t\t\t'  + Cafe_Barista_Bros.get() + "\n")
    Receipt_Text.insert(END, 'Lipton Light:\t\t\t' + Cafe_Lipton_Light.get() + "\n")
    Receipt_Text.insert(END, 'Hot Chocolate:\t\t\t'  + Cafe_Hot_Chocolate.get() + "\n")
    Receipt_Text.insert(END, 'Aloe_Drink:\t\t\t'  + Cafe_Aloe_Drink.get() + "\n")
    Receipt_Text.insert(END, 'Orange_Juice:\t\t\t'  + Cafe_Orange_Juice.get() + "\n")
    Receipt_Text.insert(END, 'Calci Yum:\t\t\t'  + Cafe_Calci_Yum.get() + "\n")
    Receipt_Text.insert(END, 'Flavoured_Water:\t\t\t'  + Cafe_Flavoured_Water.get() + "\n")
    Receipt_Text.insert(END, 'Cost of Drinks:\t\t\t' + CostofDrinks.get()+'\t\t' + '\tTaxPaid:\t\t' + PaidTax.get()+"\n")
    Receipt_Text.insert(END, 'Cost of Meals:\t\t\t' + CostofMeals.get()+ '\tSubTotal:\t\t' + SubTotal.get() + "\n")
    Receipt_Text.insert(END, 'WaiterTip:\t\t\t' + WaiterTip.get() + '\Total Cost:\t\t' + TotalCost.get() + "\n")
def Check_Value_Checkbuttons():
    if (ItemVar1.get()==1):
        EntryNachos.configure(state=NORMAL)
    elif ItemVar1.get()==0:
        EntryNachos.configure(state=DISABLED)
        Cafe_Nachos.set("0")
    if (ItemVar2.get()==1):
        EntryChicken_Sandwich.configure(state=NORMAL)
    elif ItemVar2.get()==0:
        EntryChicken_Sandwich.configure(state=DISABLED)
        Cafe_Chicken_Sandwich.set("0")
    if (ItemVar3.get()==1):
        EntrySausage_Roll.configure(state=NORMAL)
    elif ItemVar3.get()==0:
        EntrySausage_Roll.configure(state=DISABLED)
        Cafe_Sausage_Roll.set("0")
    if (ItemVar4.get()==1):
        EntryHotdog.configure(state=NORMAL)
    elif ItemVar4.get()==0:
        EntryHotdog.configure(state=DISABLED)
        Cafe_Hotdog.set("0")
    if (ItemVar5.get()==1):
        EntryPizza_Bread.configure(state=NORMAL)
    elif ItemVar5.get()==0:
        EntryPizza_Bread.configure(state=DISABLED)
        Cafe_Pizza_Bread.set("0")
    if (ItemVar6.get()==1):
        EntryPizza.configure(state=NORMAL)
    elif ItemVar6.get()==0:
        EntryPizza.configure(state=DISABLED)
        Cafe_Pizza.set("0")
    if (ItemVar7.get()==1):
        EntrySteam_Bun.configure(state=NORMAL)
    elif ItemVar7.get()==0:
        EntrySteam_Bun.configure(state=DISABLED)
        Cafe_Steam_Bun.set("0")
    if (ItemVar8.get()==1):
        EntrySoup.configure(state=NORMAL)
    elif ItemVar8.get()==0:
        EntrySoup.configure(state=DISABLED)
        Cafe_Soup.set("0")
    if (ItemVar9.get()==1):
        EntryWater.configure(state=NORMAL)
    elif ItemVar9.get()==0:
        EntryWater.configure(state=DISABLED)
        Cafe_Water.set("0")
    if (ItemVar10.get()==1):
        EntryBarista_Bros.configure(state=NORMAL)
    elif ItemVar10.get()==0:
        EntryBarista_Bros.configure(state=DISABLED)
        Cafe_Barista_Bros.set("0")
    if (ItemVar11.get()==1):
        EntryLipton_Light.configure(state=NORMAL)
    elif ItemVar11.get()==0:
        EntryLipton_Light.configure(state=DISABLED)
        Cafe_Lipton_Light.set("0")
    if (ItemVar12.get()==1):
        EntryHot_Chocolate.configure(state=NORMAL)
    elif ItemVar12.get()==0:
        EntryHot_Chocolate.configure(state=DISABLED)
        Cafe_Hot_Chocolate.set("0")
    if (ItemVar13.get()==1):
        EntryAloe_Drink.configure(state=NORMAL)
    elif ItemVar13.get()==0:
        EntryAloe_Drink.configure(state=DISABLED)
        Cafe_Aloe_Drink.set("0")
    if (ItemVar14.get()==1):
        EntryOrange_Juice.configure(state=NORMAL)
    elif ItemVar14.get()==0:
        EntryOrange_Juice.configure(state=DISABLED)
        Cafe_Orange_Juice.set("0")
    if (ItemVar15.get()==1):
        EntryCalci_Yum.configure(state=NORMAL)
    elif ItemVar15.get()==0:
        EntryCalci_Yum.configure(state=DISABLED)
        Cafe_Calci_Yum.set("0")
    if (ItemVar16.get()==1):    
        EntryFlavoured_Water.configure(state=NORMAL)
    elif ItemVar16.get()==0:
        EntryFlavoured_Water.configure(state=DISABLED)
        Cafe_Flavoured_Water.set("0")
#===========================================Frames for the Cafe Menu===========================================
FrameOne = Frame(root, width = 900, height = 350, bd = 8, relief ="raise", background = "light blue")
FrameOne.pack(side=RIGHT)
FrameTwo = Frame(root, width = 440, height = 650, bd = 8, relief = "raise", background = "light blue")
FrameTwo.pack(side=LEFT)
FrameOneFront = Frame(FrameOne, width = 900, height = 330, bd = 8, relief = "raise", background = "light blue")
FrameOneFront.pack(side=TOP)
FrameTwoFront = Frame(FrameOne, width = 900, height = 320, bd = 6, relief = "raise", background = "light blue")
FrameTwoFront.pack(side=BOTTOM)
TextFrame = Frame(FrameTwo, width = 440, height = 450, bd = 12, relief = "raise", background = "light blue")
TextFrame.pack(side=BOTTOM)
MainFrontOne = Frame(FrameTwo, width = 440, height = 330, bd = 16, relief = "raise", background = "light blue") # Top left left
MainFrontOne.pack(side=TOP)
MainFrontTwo = Frame(FrameOneFront, width = 450, height = 425, bd = 16, relief = "raise", background = "light blue")# Top Left
MainFrontTwo.pack(side=LEFT)
MainFrontThird = Frame(FrameOneFront, width = 450, height = 425, bd = 16, relief = "raise", background = "light blue")# Top Right
MainFrontThird.pack(side=RIGHT)
MainFrontFourth = Frame(FrameTwoFront, width = 450, height = 175, bd = 14, relief = "raise", background = "light blue")#Botom left
MainFrontFourth.pack(side=LEFT)
MainFrontFifth = Frame(FrameTwoFront, width = 450, height = 175, bd = 14, relief = "raise", background = "light blue")#Bottom right 
MainFrontFifth.pack(side=RIGHT)
#=======================================================Variables for the program=============================================
DateofOrder = StringVar()
Receipt_Ref = StringVar()
PaidTax = StringVar()
SubTotal = StringVar()
TotalCost = StringVar()
CostofMeals = StringVar()
CostofDrinks = StringVar()
WaiterTip = StringVar()
ItemVar1 = IntVar()
ItemVar2 = IntVar()
ItemVar3 = IntVar()
ItemVar4 = IntVar()
ItemVar5 = IntVar()
ItemVar6 = IntVar()
ItemVar7 = IntVar()
ItemVar8 = IntVar()
ItemVar9 = IntVar()
ItemVar10 = IntVar()
ItemVar11 = IntVar()
ItemVar12 = IntVar()
ItemVar13 = IntVar()
ItemVar14 = IntVar()
ItemVar15 = IntVar()
ItemVar16 = IntVar()
Cafe_Nachos=StringVar()
Cafe_Chicken_Sandwich=StringVar()
Cafe_Sausage_Roll=StringVar()
Cafe_Hotdog=StringVar()
Cafe_Pizza_Bread=StringVar()
Cafe_Pizza=StringVar()
Cafe_Steam_Bun=StringVar()
Cafe_Soup=StringVar()
Cafe_Water=StringVar()
Cafe_Barista_Bros=StringVar()
Cafe_Lipton_Light=StringVar()
Cafe_Hot_Chocolate=StringVar()
Cafe_Aloe_Drink=StringVar()
Cafe_Orange_Juice=StringVar()
Cafe_Calci_Yum=StringVar()
Cafe_Flavoured_Water=StringVar()
Cafe_Nachos.set("0")
Cafe_Chicken_Sandwich.set("0")
Cafe_Sausage_Roll.set("0")
Cafe_Hotdog.set("0")
Cafe_Pizza_Bread.set("0")
Cafe_Pizza.set("0")
Cafe_Steam_Bun.set("0")
Cafe_Soup.set("0")
Cafe_Water.set("0")
Cafe_Barista_Bros.set("0")
Cafe_Lipton_Light.set("0")
Cafe_Hot_Chocolate.set("0")
Cafe_Aloe_Drink.set("0")
Cafe_Orange_Juice.set("0")
Cafe_Calci_Yum.set("0")
Cafe_Flavoured_Water.set("0")
DateofOrder.set(time.strftime("%d/%m/%Y"))
#=======================================Checkbuttons for Snacks/Meals=============================================================
FirstLabel = Label(MainFrontTwo, font=('arial',13, 'bold'),text = "Foods/Snacks",bd=10, background = "light blue")
FirstLabel.grid(row=0,column=0)
Nachos = Checkbutton(MainFrontTwo, text ="Latte \t\t\t\t",  command = Check_Value_Checkbuttons,variable = ItemVar1, onvalue = 1, background = "light blue", offvalue = 0, font=('arial',12, 'bold')).grid(row=1, sticky =W)
Chicken_Sandwich = Checkbutton(MainFrontTwo, text ="Chicken Sandwich \t", command = Check_Value_Checkbuttons, variable = ItemVar2, onvalue = 1, offvalue = 0, font=('arial',12, 'bold'), background = "light blue").grid(row=2, sticky =W)
Sausage_Roll = Checkbutton(MainFrontTwo, text ="Sausage Roll \t", command = Check_Value_Checkbuttons, variable = ItemVar3, onvalue = 1, offvalue = 0, font=('arial',12, 'bold'), background = "light blue").grid(row=3, sticky =W)
Hotdog = Checkbutton(MainFrontTwo, text ="Hot Dog \t", command = Check_Value_Checkbuttons, variable = ItemVar4, onvalue = 1, offvalue = 0, font=('arial',12, 'bold'), background = "light blue").grid(row=4, sticky =W)
Pizza_Bread = Checkbutton(MainFrontTwo, text ="PizzaBread \t",  command = Check_Value_Checkbuttons,variable = ItemVar5, onvalue = 1, offvalue = 0, font=('arial',12, 'bold'), background = "light blue").grid(row=5, sticky =W)
Pizza = Checkbutton(MainFrontTwo, text ="Pizza \t",  command = Check_Value_Checkbuttons,variable = ItemVar6, onvalue = 1, offvalue = 0, font=('arial',12, 'bold'), background = "light blue").grid(row=6, sticky =W)
Steam_Bun = Checkbutton(MainFrontTwo, text ="SteamBun \t", command = Check_Value_Checkbuttons, variable = ItemVar7, onvalue = 1, offvalue = 0, font=('arial',12, 'bold'), background = "light blue").grid(row=7, sticky =W)
Soup = Checkbutton(MainFrontTwo, text ="Soup \t", command = Check_Value_Checkbuttons, variable = ItemVar8, onvalue = 1, offvalue = 0, font=('arial',12, 'bold'), background = "light blue").grid(row=8, sticky =W)
#======================================Checkbuttons for Drinks/Bevarages==================================================================
SecondLabel = Label(MainFrontThird, font=('arial',13, 'bold'),text = "Drinks/Beverages",bd=10, background = "light blue")
SecondLabel.grid(row=0,column=0)
Water = Checkbutton(MainFrontThird, text ="Water \t\t\t\t", command = Check_Value_Checkbuttons, variable = ItemVar9, onvalue = 1, offvalue = 0, font=('arial',12, 'bold'), background = "light blue").grid(row=1, sticky =W)
Barista_Bros = Checkbutton(MainFrontThird, text ="Barista Bros \t", command = Check_Value_Checkbuttons, variable = ItemVar10, onvalue = 1, offvalue = 0, font=('arial',12, 'bold'), background = "light blue").grid(row=2, sticky =W)
Lipton_Light = Checkbutton(MainFrontThird, text ="Lipton Light \t", command = Check_Value_Checkbuttons, variable = ItemVar11, onvalue = 1, offvalue = 0, font=('arial',12, 'bold'), background = "light blue").grid(row=3, sticky =W)
Hot_Chocolate = Checkbutton(MainFrontThird, text ="Hot Chocolate \t", command = Check_Value_Checkbuttons, variable = ItemVar12, onvalue = 1, offvalue = 0, font=('arial',12, 'bold'), background = "light blue").grid(row=4, sticky =W)
Aloe_Drink = Checkbutton(MainFrontThird, text ="Aloe Drink \t", command = Check_Value_Checkbuttons, variable = ItemVar13, onvalue = 1, offvalue = 0, font=('arial',12, 'bold'), background = "light blue").grid(row=5, sticky =W)
Orange_Juice = Checkbutton(MainFrontThird, text ="Orange Juice \t", command = Check_Value_Checkbuttons, variable = ItemVar14, onvalue = 1, offvalue = 0, font=('arial',12, 'bold'), background = "light blue").grid(row=6, sticky =W)
Calci_Yum = Checkbutton(MainFrontThird, text ="Calci Yum \t", command = Check_Value_Checkbuttons, variable = ItemVar15, onvalue = 1, offvalue = 0, font=('arial',12, 'bold'), background = "light blue").grid(row=7, sticky =W)
Flavoured_Water = Checkbutton(MainFrontThird, text ="Flavoured Water \t",  command = Check_Value_Checkbuttons,variable = ItemVar16, onvalue = 1, offvalue = 0, font=('arial',12, 'bold'), background = "light blue").grid(row=8, sticky =W)
#=============================================Entry Widget for Snacks/Meals======================================
EntryNachos = Entry(MainFrontTwo, font=('arial',10, 'bold'), bd = 8, width = 6, justify ='left',textvariable = Cafe_Nachos, state = DISABLED)
EntryNachos.grid(row =1, column = 1)
EntryChicken_Sandwich = Entry(MainFrontTwo, font=('arial',10, 'bold'), bd = 8, width = 6, justify ='left',textvariable = Cafe_Chicken_Sandwich, state = DISABLED)
EntryChicken_Sandwich.grid(row =2, column = 1)
EntrySausage_Roll = Entry(MainFrontTwo, font=('arial',10, 'bold'), bd = 8, width = 6, justify ='left',textvariable = Cafe_Sausage_Roll, state = DISABLED)
EntrySausage_Roll.grid(row =3, column = 1)
EntryHotdog = Entry(MainFrontTwo, font=('arial',10, 'bold'), bd = 8, width = 6, justify ='left',textvariable = Cafe_Hotdog, state = DISABLED)
EntryHotdog.grid(row =4, column = 1)
EntryPizza_Bread = Entry(MainFrontTwo, font=('arial',10, 'bold'), bd = 8, width = 6, justify ='left',textvariable = Cafe_Pizza_Bread, state = DISABLED)
EntryPizza_Bread.grid(row =5, column = 1)
EntryPizza = Entry(MainFrontTwo, font=('arial',10, 'bold'), bd = 8, width = 6, justify ='left',textvariable = Cafe_Pizza ,state = DISABLED)
EntryPizza.grid(row =6, column = 1)
EntrySteam_Bun = Entry(MainFrontTwo, font=('arial',10, 'bold'), bd = 8, width = 6, justify ='left',textvariable = Cafe_Steam_Bun, state = DISABLED)
EntrySteam_Bun.grid(row =7, column = 1)
EntrySoup = Entry(MainFrontTwo, font=('arial',10, 'bold'), bd = 8, width = 6, justify ='left', textvariable = Cafe_Soup, state = DISABLED)
EntrySoup.grid(row =8, column = 1)
#=============================================Entry Widgets for Drinks/Beverages=======================================
EntryWater = Entry(MainFrontThird, font=('arial',10, 'bold'), bd = 8, width = 6, justify ='left',textvariable = Cafe_Water, state = DISABLED)
EntryWater.grid(row =1, column = 1)
EntryBarista_Bros = Entry(MainFrontThird, font=('arial',10, 'bold'), bd = 8, width = 6, justify ='left',textvariable = Cafe_Barista_Bros, state = DISABLED)
EntryBarista_Bros.grid(row =2, column = 1)
EntryLipton_Light = Entry(MainFrontThird, font=('arial',10, 'bold'), bd = 8, width = 6, justify ='left',textvariable =Cafe_Lipton_Light, state = DISABLED)
EntryLipton_Light.grid(row =3, column = 1)
EntryHot_Chocolate = Entry(MainFrontThird, font=('arial',10, 'bold'), bd = 8, width = 6, justify ='left',textvariable =Cafe_Hot_Chocolate, state = DISABLED)
EntryHot_Chocolate.grid(row =4, column = 1)
EntryAloe_Drink = Entry(MainFrontThird, font=('arial',10, 'bold'), bd = 8, width = 6, justify ='left',textvariable = Cafe_Aloe_Drink, state = DISABLED)
EntryAloe_Drink.grid(row =5, column = 1)
EntryOrange_Juice = Entry(MainFrontThird, font=('arial',10, 'bold'), bd = 8, width = 6, justify ='left',textvariable = Cafe_Orange_Juice, state = DISABLED)
EntryOrange_Juice.grid(row =6, column = 1)
EntryCalci_Yum = Entry(MainFrontThird, font=('arial',10, 'bold'), bd = 8, width = 6, justify ='left',textvariable = Cafe_Calci_Yum, state = DISABLED)
EntryCalci_Yum.grid(row =7, column = 1)
EntryFlavoured_Water = Entry(MainFrontThird, font=('arial',10, 'bold'), bd = 8, width = 6, justify ='left', textvariable = Cafe_Flavoured_Water, state = DISABLED)
EntryFlavoured_Water.grid(row =8, column = 1)
#=================================================Labels and Entries for Costs and Waiter Tip=================================================
LabelCostofDrinks=Label(MainFrontFourth, font=('arial', 12, 'bold'), text = "Cost of Drinks\t\t", bd = 8, background = "light blue")
LabelCostofDrinks.grid(row=2, column =0, sticky =W)
EntryCostofDrinks = Entry(MainFrontFourth, font=('arial',12, 'bold'), bd = 8, justify='left', insertwidth = 2, textvariable = CostofDrinks, state = DISABLED)
EntryCostofDrinks.grid(row=2, column=1, sticky=W)

LabelCostofMeals=Label(MainFrontFourth, font=('arial', 12, 'bold'), text = "Cost of Meals", bd = 8, background = "light blue")
LabelCostofMeals.grid(row=3, column =0, sticky =W)
EntryCostofMeals = Entry(MainFrontFourth, font=('arial',12, 'bold'), bd = 8, justify='left', insertwidth =2, textvariable = CostofMeals, state = DISABLED)
EntryCostofMeals.grid(row=3, column=1, sticky=W)

LabelWaiterTip=Label(MainFrontFourth, font=('arial', 12, 'bold'), text = "Waiter Tip\t\t", bd = 8, background = "light blue")
LabelWaiterTip.grid(row=4, column =0, sticky =W)
EntryWaiterTip = Entry(MainFrontFourth, font=('arial',12, 'bold'), bd = 8, justify='left', insertwidth  =2, textvariable = WaiterTip, state = DISABLED)
EntryWaiterTip.grid(row=4, column=1, sticky=W)
#======================================================Labels and Entries for Tax, Total Cost and Subtotal============================================
LabelPaidTax=Label(MainFrontFifth, font=('arial', 12, 'bold'), text = "Paid Tax\t\t\t", bd = 8, background = "light blue")
LabelPaidTax.grid(row=2, column =0, sticky =W)
EntryPaidTax = Entry(MainFrontFifth, font=('arial',12, 'bold'), bd = 8, justify='left', insertwidth =2, textvariable =PaidTax, state = DISABLED)
EntryPaidTax.grid(row=2, column=1, sticky=W)

LabelSubTotal=Label(MainFrontFifth, font=('arial', 12, 'bold'), text = "Sub Total", bd = 8, background = "light blue")
LabelSubTotal.grid(row=3, column =0, sticky =W)
EntrySubTotal = Entry(MainFrontFifth, font=('arial',12, 'bold'), bd = 8, justify='left', insertwidth = 2, textvariable =SubTotal, state = DISABLED)
EntrySubTotal.grid(row=3, column=1, sticky=W)

LabelTotalCost=Label(MainFrontFifth, font=('arial', 12, 'bold'), text = "Total Cost", bd = 8, background = "light blue")
LabelTotalCost.grid(row=4, column =0, sticky =W)
EntryTotalCost = Entry(MainFrontFifth, font=('arial',12, 'bold'), bd = 8, justify='left', insertwidth = 2, textvariable = TotalCost, state = DISABLED)
EntryTotalCost.grid(row=4, column=1, sticky=W)
#==================================================Buttons for the Cafe Menu=====================================================
ButtonTotal = Button(MainFrontOne, padx = 16, pady = 1, bd =4,font=('arial', 10, 'bold'), width = 5, text = "Total", command = CostofItem).grid(row=0, column=0)
ButtonReset = Button(MainFrontOne, padx = 16, pady = 1, bd =4,font=('arial', 10, 'bold'), width = 5, text = "Reset", command =ResetData).grid(row=0, column=2)
ButtonExit = Button(MainFrontOne, padx = 16, pady = 1, bd =4,font=('arial', 10, 'bold'), width = 5, text = "Exit", command =ExitButton).grid(row=0, column=3)
#=================================================Information=================================================
Receipt_Text = Text(TextFrame, font=('arial',10, 'bold'), bd = 8, width = 59)
Receipt_Text.grid(row =1, column = 0)
root.mainloop() #Runs application
